# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# Stable rustfmt config. A whole-tree `cargo fmt` still rewrites denser committed style; CI runs
# `cargo fmt --check` as informational. Prefer formatting files you touch.
edition = "2021"
