# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
[package]
name = "atlas-license-tool"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "atlas-license-tool"
path = "src/main.rs"

[dependencies]
atlas-license = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
jsonwebtoken = { workspace = true }
ring = { workspace = true }
anyhow = { workspace = true }
