# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Atlas-Commercial
[package]
name = "atlas-driver-rgw"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
sha2 = "0.10"
hex = "0.4"
rusty-s3 = { version = "0.10", features = ["full"] }
url = "2"
percent-encoding = "2"
