# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
# Namespace for DataBridge edge databases + their operators/streaming (matches EDGE_NAMESPACE
# in atlas-databridge::pipeline). Edge CloudNativePG / Percona clusters and Debezium connectors
# are created here by the migration pipeline.
apiVersion: v1
kind: Namespace
metadata:
  name: zyvor-databridge
  labels:
    zyvor.dev/component: databridge
