# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
# RGW object store (S3-compatible) + an object-bucket StorageClass for backups/exports (PDF §2, §9.9).
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: zyvor-rgw
  namespace: rook-ceph
spec:
  metadataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: false
  dataPool:
    failureDomain: host
    replicated:
      size: 3
      requireSafeReplicaSize: false
  preservePoolsOnDelete: false
  gateway:
    port: 80
    instances: 1
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zyvor-rgw-bucket
  labels:
    zyvor.dev/storage-backend: ceph
    zyvor.dev/storage-kind: object
provisioner: rook-ceph.ceph.rook.io/bucket
reclaimPolicy: Delete
parameters:
  objectStoreName: zyvor-rgw
  objectStoreNamespace: rook-ceph
