# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Atlas-Commercial
# Only for the fake/k8s-driver shape — the real-Ceph shape runs in ceph.rookNamespace, which Rook
# itself owns and creates; Atlas must not manage that namespace's lifecycle.
{{- if not .Values.ceph.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    zyvor.dev/component: control-plane
{{- end }}
