# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "atlas.fullname" . }}
  namespace: {{ include "atlas.namespace" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "atlas.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
    {{- if .Values.service.grpc.enabled }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.grpc.nodePort }}
      {{- end }}
    {{- end }}
    {{- if .Values.service.https.enabled }}
    - name: https
      port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.https.nodePort }}
      {{- end }}
    {{- end }}
