# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: LicenseRef-Zyvor-Production-1.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas.name" . }}-gateway
  namespace: {{ include "atlas.namespace" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
