# Copyright (c) 2026 ZyvorAI Labs Private Limited. All rights reserved.
[package]
name = "atlas-license"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
jsonwebtoken = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
ring = { workspace = true }
