# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Atlas-Commercial
# Syncs secret/atlas-demo/gateway-auth from Vault into K8s Secret
# external-secrets/atlas-demo-gateway-auth every 30s. Deliberately a standalone demo secret, not
# the live atlas-gateway-auth Secret — see up.sh's header for why, and how to point this at the
# real one once a real Vault is available.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlas-demo-gateway-auth
  namespace: external-secrets
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-lab
    kind: SecretStore
  target:
    name: atlas-demo-gateway-auth
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: atlas-demo/gateway-auth
        property: jwt-secret
    - secretKey: admin-password
      remoteRef:
        key: atlas-demo/gateway-auth
        property: admin-password
