# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Atlas-Commercial
# Points External Secrets Operator at the lab Vault, authenticating as the external-secrets
# ServiceAccount via Vault's Kubernetes auth method (role "atlas-demo-reader", see up.sh).
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-lab
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault-lab.svc:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "atlas-demo-reader"
          serviceAccountRef:
            name: "external-secrets"
